'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_MS_DRIVER_INFO
    Public Property DRIVER_INFO_ID As Decimal
    Public Property TRANS_ID As String
    Public Property DRIVER_LICENSE As String
    Public Property DRIVER_NAME As String
    Public Property ADDRESS As String
    Public Property TEL As String
    Public Property CREATED_BY As Nullable(Of Long)
    Public Property CREATED_DATE As Nullable(Of Date)
    Public Property UPDATED_BY As Nullable(Of Long)
    Public Property UPDATED_DATE As Nullable(Of Date)
    Public Property IS_DELETED As String
    Public Property CANCEL_ID As String
    Public Property CANCEL_DATE As Nullable(Of Date)
    Public Property ENT_ID As Nullable(Of Long)
    Public Property CMP_ID As Nullable(Of Long)
    Public Property FAL_ID As Nullable(Of Long)
    Public Property USR_ID As Nullable(Of Long)
    Public Property BPN_ID As Nullable(Of Long)
    Public Property STATUS_IX As Nullable(Of Long)

End Class
