'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_MS_TRUCK_INFO
    Public Property TRUCK_INFO_ID As Decimal
    Public Property COMPANY_ID As String
    Public Property TRUCK_ID As String
    Public Property PROVINCE As String
    Public Property TRUCK_LICENSE As String
    Public Property TRUCK_TYPE As String
    Public Property TRUCK_STATUS As Nullable(Of Long)
    Public Property EXPIRATION_DATE As Nullable(Of Date)
    Public Property SAFE_WEIGHT As Nullable(Of Long)
    Public Property CREATED_BY As Nullable(Of Long)
    Public Property CREATED_DATE As Nullable(Of Date)
    Public Property UPDATED_BY As String
    Public Property UPDATED_DATE As Nullable(Of Date)
    Public Property IS_DELETED As String
    Public Property CANCEL_ID As String
    Public Property CANCEL_DATE As Nullable(Of Date)
    Public Property ENT_ID As Nullable(Of Long)
    Public Property CMP_ID As Nullable(Of Long)
    Public Property FAL_ID As Nullable(Of Long)
    Public Property USR_ID As Nullable(Of Long)
    Public Property BPN_ID As Nullable(Of Long)
    Public Property STATUS As Nullable(Of Long)

End Class
