'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_MS_TERMINAL
    Public Property TERMINAL_ID As Decimal
    Public Property TERMINAL_CODE As String
    Public Property TERMINAL_NAME As String
    Public Property OPERATION As String
    Public Property LOCATION As String
    Public Property WEBSITE As String
    Public Property TEL As Nullable(Of Decimal)
    Public Property AUTHORIZATION_CODE As String
    Public Property CREATED_BY As Nullable(Of Long)
    Public Property CREATED_DATE As Nullable(Of Date)
    Public Property UPDATED_BY As Nullable(Of Long)
    Public Property UPDATED_DATE As Nullable(Of Date)
    Public Property IS_DELETED As String
    Public Property CANCEL_BY As String
    Public Property CANCEL_DATE As Nullable(Of Date)
    Public Property ENT_ID As Nullable(Of Long)
    Public Property CMP_ID As Nullable(Of Long)
    Public Property FAL_ID As Nullable(Of Long)
    Public Property USR_ID As Nullable(Of Long)
    Public Property BPN_ID As Nullable(Of Long)
    Public Property STATUS_IX As Nullable(Of Long)
    Public Property CARD_ID As String
    Public Property CONNECT_NAME As String
    Public Property FAX As String
    Public Property EMAIL As String
    Public Property ADDRESS As String
    Public Property USER_NAME As String
    Public Property PASSWORD As String
    Public Property CONFIRMPASSWORD As String

End Class
