'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_MS_TRUCK_COMP
    Public Property TRUCK_COMP_ID As Decimal
    Public Property TRUCK_CODE As String
    Public Property TRUCK_NAME As String
    Public Property TYPE As String
    Public Property CARD_ID As String
    Public Property CARD_BGN As Nullable(Of Date)
    Public Property BGN_DATE As Nullable(Of Date)
    Public Property CORPORATE_NO As String
    Public Property ADDRESS_NO As String
    Public Property BUILDING As String
    Public Property FLOOR As String
    Public Property VILLAGE_NO As String
    Public Property VILLAGE As String
    Public Property SOI As String
    Public Property ROAD As String
    Public Property DISTRICT_ID As String
    Public Property AMPHUR_ID As String
    Public Property PROVINCE_ID As String
    Public Property ZIPCODE As String
    Public Property TEL As String
    Public Property FAX As String
    Public Property NEARLOCATE As String
    Public Property CONTACT_NAME As String
    Public Property MOBILE As String
    Public Property CREATED_BY As String
    Public Property CREATED_DATE As Nullable(Of Date)
    Public Property UPDATED_BY As Nullable(Of Decimal)
    Public Property UPDATED_DATE As Nullable(Of Date)
    Public Property IS_DELETED As String
    Public Property CANCEL_BY As String
    Public Property CANCEL_DATE As Nullable(Of Date)
    Public Property ENT_ID As Nullable(Of Long)
    Public Property CMP_ID As Nullable(Of Long)
    Public Property FAL_ID As Nullable(Of Long)
    Public Property USR_ID As Nullable(Of Long)
    Public Property BPN_ID As Nullable(Of Long)
    Public Property STATUS_IX As Nullable(Of Long)
    Public Property CARD_EXPIRE As Date
    Public Property USERNAME As String
    Public Property PASSWORD As String
    Public Property CONFIRMPASSWORD As String

End Class
