'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_RN_RUNNUMBER
    Public Property RUNID As Long
    Public Property RUNCODE As String
    Public Property RUNNUMBER As Long
    Public Property RUNNAME As String
    Public Property STATUS As Boolean
    Public Property RUNTYPE As String

End Class
