'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TQ_TRUCK_VISIT_HIS
    Public Property TRUCK_VISIT_HIS_ID As Decimal
    Public Property TRUCK_VISIT_NO As Nullable(Of Decimal)
    Public Property TRUCK_VISIT_DATE As Nullable(Of Date)
    Public Property TRUCK_ID As Nullable(Of Long)
    Public Property START_TIME As Nullable(Of Date)
    Public Property END_TIME As Nullable(Of Date)
    Public Property DURATION As Nullable(Of Date)
    Public Property TERMINAL_ID As String
    Public Property SUB_GATE_NO As String
    Public Property FILE_NAME As String
    Public Property CREATED_BY As Nullable(Of Long)
    Public Property CREATED_DATE As Nullable(Of Date)
    Public Property UPDATED_BY As Nullable(Of Long)
    Public Property UPDATED_DATE As Nullable(Of Date)
    Public Property IS_DELETED As String
    Public Property CANCEL_BY As Nullable(Of Long)
    Public Property CANCEL_DATE As Nullable(Of Date)
    Public Property ENT_ID As Nullable(Of Long)
    Public Property CMP_ID As Nullable(Of Long)
    Public Property FAL_ID As Nullable(Of Long)
    Public Property USR_ID As Nullable(Of Long)
    Public Property BPN_ID As Nullable(Of Long)
    Public Property STATUS_IX As Nullable(Of Long)

End Class
