'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm_Truck_Comp

    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

    '''<summary>
    '''TRUCK_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRUCK_CODE As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TRUCK_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRUCK_NAME As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E31 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ADDRESS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADDRESS As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CARD_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CARD_ID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''CONTACT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CONTACT_NAME As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TEL As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''FAX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FAX As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E4 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Type As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E3 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E5 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''eMailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eMailTextBox As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E9 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E8 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E10 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E11 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E12 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E13 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E14 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E15 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E27 As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''ASPxFormLayout1_E19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E19 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E29 As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''ASPxFormLayout1_E21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E21 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E22 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E23 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E24 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxFormLayout1_E25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E25 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''USERNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents USERNAME As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''confirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmPassword As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ratingControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ratingControl As Global.DevExpress.Web.ASPxRatingControl

    '''<summary>
    '''ratingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ratingLabel As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''Captcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Captcha As Global.DevExpress.Web.ASPxCaptcha

    '''<summary>
    '''ASPxFormLayout1_Button_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_Button_OK As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''EF_TruckComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EF_TruckComp As Global.DevExpress.Data.Linq.EntityServerModeDataSource
End Class
